Starting the meeting, the team discussed about excluding GBP cases from the oversight metric calculation. They aligned that GBP cases should be excluded from the metric calculation.
The team conducted a comprehensive review of the March 2025 Global Complaint Oversight Metrics Dashboard (GCV). Overall, Global Complaint Oversight Metrics successfully met their targets for all metrics. At the regional level, APAC, LATAM and NA were green in all metrics. For EMEA, all metrics were green except for Triage Timeliness, which was in yellow status. The EMA team expressed that this was attributable to the GBP cases in the region. To understand why the late triage cases, discussing the exploratory analysis which shows the ‘Time in Step’ interval, it was determined that majority of the late triage cases were driven by priority cases which are targeted to close in two business days. 
The team reviewed the End-to-End Global Complaint Oversight Metrics, the metrics met their goals except for Complaint Aging which has yellow status. It was established the case that led to this status was created in PQMS past 45 days. 
Examining the metric for the past three months shows that APAC was green for all metric except for Triage Timeliness in January 2025 but returned in the last month. LATAM and NA are green for all metric for the three months period. For EMEA, the Triage Timeliness has yellow status in January 2025 but green in February and returned to yellow status in March 2025. The EMEA Complaint Timeliness was green in January 2025, but yellow in February 2025 and returned green in March 2025 while MFT and Change Log metrics were green for the three months. As per procedure no further action is required at this time.
The team examined the Complaint Open Overdue Cases using the Complaint Oversight metrics dashboard. 
In conclusion, the meeting was highly successful, reflecting strong Regional and Global complaint vigilance performance in March 2025.


The team conducted a comprehensive review of the February 2025 Global Complaint Oversight Metrics Dashboard. Overall, Global Complaint Oversight Metrics successfully met their targets for all metrics except for Complaint Aging Overdue, which indicated a "yellow" status. Complaint volumes in December 2024 showed an increase compared to the previous month. Key metrics, including Complaint Timeliness, MFT Timeliness, Change Log Timeliness, Complaint Aging, Trending Report Timeliness, and MDR Submission Timeliness, indicated a "green" status, while Complaint Aging Overdue indicated "yellow."
A deeper review revealed that Complaint Timeliness, MFT Timeliness, and Change Log Timeliness have been "green" over the past three months for NA and LATAM. While APAC for the last three months has been green in other metrics except for Triage Timeliness which was red in December 2024 and January 2025, however indicated “green” in February 2025. Reviewing EMEA, the complaint for the past two months showed that complaint Timeliness indicated “yellow” in February 2025 while MFT and Change Log Timeliness were “green” in the past three months. Triage Timeliness were in yellow in December 2024 and January 2025, however indicated “green” in February 2025. 
The review further revealed that complaint volumes globally were higher than in the previous month. The Word Cloud analysis highlighted commonly used terms in complaint descriptions for February 2025 for the top eight products in respective regions.
In conclusion, the meeting was highly successful, reflecting strong Regional and Global complaint vigilance performance in February 2025.
